import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Layanan",
    description: "Generated by create next app",
    keywords: "top up game, game, top up, voucher game",
    authors: {
        url: "https://gasskeuntopup.com",
        name: "Gasskeun Topup",
    },
};

export default function LayananLayout({ children }: { children: React.ReactNode }) {
    return <div>{children}</div>;
}
